# Generated by Django 5.0.4 on 2024-05-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('product_title', 'product_price'), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='product',
            name='product_preview',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Превью'),
        ),
    ]
