# Generated by Django 5.0.4 on 2024-05-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_options_alter_product_product_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_preview',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Превью'),
        ),
    ]
